# CMake generated Testfile for 
# Source directory: C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util
# Build directory: C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_util_counting_includer "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Debug/shaderc_util_counting_includer_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_util_counting_includer "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Release/shaderc_util_counting_includer_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_util_counting_includer "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/MinSizeRel/shaderc_util_counting_includer_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_util_counting_includer "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/RelWithDebInfo/shaderc_util_counting_includer_test.exe")
else()
  add_test(shaderc_util_counting_includer NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_util_string_piece "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Debug/shaderc_util_string_piece_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_util_string_piece "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Release/shaderc_util_string_piece_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_util_string_piece "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/MinSizeRel/shaderc_util_string_piece_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_util_string_piece "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/RelWithDebInfo/shaderc_util_string_piece_test.exe")
else()
  add_test(shaderc_util_string_piece NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_util_format "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Debug/shaderc_util_format_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_util_format "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Release/shaderc_util_format_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_util_format "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/MinSizeRel/shaderc_util_format_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_util_format "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/RelWithDebInfo/shaderc_util_format_test.exe")
else()
  add_test(shaderc_util_format NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_util_file_finder "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Debug/shaderc_util_file_finder_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_util_file_finder "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Release/shaderc_util_file_finder_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_util_file_finder "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/MinSizeRel/shaderc_util_file_finder_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_util_file_finder "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/RelWithDebInfo/shaderc_util_file_finder_test.exe")
else()
  add_test(shaderc_util_file_finder NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_util_io "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Debug/shaderc_util_io_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_util_io "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Release/shaderc_util_io_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_util_io "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/MinSizeRel/shaderc_util_io_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_util_io "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/RelWithDebInfo/shaderc_util_io_test.exe")
else()
  add_test(shaderc_util_io NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_util_message "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Debug/shaderc_util_message_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_util_message "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Release/shaderc_util_message_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_util_message "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/MinSizeRel/shaderc_util_message_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_util_message "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/RelWithDebInfo/shaderc_util_message_test.exe")
else()
  add_test(shaderc_util_message NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_util_mutex "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Debug/shaderc_util_mutex_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_util_mutex "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Release/shaderc_util_mutex_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_util_mutex "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/MinSizeRel/shaderc_util_mutex_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_util_mutex "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/RelWithDebInfo/shaderc_util_mutex_test.exe")
else()
  add_test(shaderc_util_mutex NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_util_compiler "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Debug/shaderc_util_compiler_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_util_compiler "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/Release/shaderc_util_compiler_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_util_compiler "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/MinSizeRel/shaderc_util_compiler_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_util_compiler "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc_util/RelWithDebInfo/shaderc_util_compiler_test.exe")
else()
  add_test(shaderc_util_compiler NOT_AVAILABLE)
endif()
