# CMake generated Testfile for 
# Source directory: C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc
# Build directory: C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_shaderc "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Debug/shaderc_shaderc_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_shaderc "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Release/shaderc_shaderc_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_shaderc "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/MinSizeRel/shaderc_shaderc_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_shaderc "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/RelWithDebInfo/shaderc_shaderc_test.exe")
else()
  add_test(shaderc_shaderc NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_shaderc_cpp "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Debug/shaderc_shaderc_cpp_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_shaderc_cpp "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Release/shaderc_shaderc_cpp_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_shaderc_cpp "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/MinSizeRel/shaderc_shaderc_cpp_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_shaderc_cpp "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/RelWithDebInfo/shaderc_shaderc_cpp_test.exe")
else()
  add_test(shaderc_shaderc_cpp NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_combined_shaderc "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Debug/shaderc_combined_shaderc_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_combined_shaderc "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Release/shaderc_combined_shaderc_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_combined_shaderc "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/MinSizeRel/shaderc_combined_shaderc_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_combined_shaderc "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/RelWithDebInfo/shaderc_combined_shaderc_test.exe")
else()
  add_test(shaderc_combined_shaderc NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_combined_shaderc_cpp "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Debug/shaderc_combined_shaderc_cpp_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_combined_shaderc_cpp "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Release/shaderc_combined_shaderc_cpp_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_combined_shaderc_cpp "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/MinSizeRel/shaderc_combined_shaderc_cpp_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_combined_shaderc_cpp "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/RelWithDebInfo/shaderc_combined_shaderc_cpp_test.exe")
else()
  add_test(shaderc_combined_shaderc_cpp NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(shaderc_c_smoke_test "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Debug/shaderc_c_smoke_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(shaderc_c_smoke_test "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/Release/shaderc_c_smoke_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(shaderc_c_smoke_test "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/MinSizeRel/shaderc_c_smoke_test.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(shaderc_c_smoke_test "C:/Users/ziyad/Documents/SPIRV-viewer/lib/shaderc/libshaderc/RelWithDebInfo/shaderc_c_smoke_test.exe")
else()
  add_test(shaderc_c_smoke_test NOT_AVAILABLE)
endif()
